[build]
builder = "nixpacks"

[deploy]
startCommand = "java -Dspring.profiles.active=railway -Dserver.port=$PORT -jar target/detailing-1.0.0.jar"

[build.env]
MAVEN_ARGS = "clean package -DskipTests"
